import { DiscoverEvent } from '../models/DiscoverEvent';

const allEvents: DiscoverEvent[] = [
  // Technology
  {
    id: 101,
    title: 'Tech Innovation Summit 2026',
    description: 'Join the biggest technology conference in Southeast Asia featuring keynotes, workshops, and networking.',
    imageSrc: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    date: 'Jul 15, 2026',
    location: 'BGC, Taguig City',
    attendees: '2,500',
    category: 'Technology',
    isPrivate: false,
  },
  {
    id: 102,
    title: 'AI Developers Conference',
    description: 'Deep dive into the future of artificial intelligence with leading researchers and engineers.',
    imageSrc: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    date: 'Aug 22, 2026',
    location: 'Makati City',
    attendees: '1,200',
    category: 'Technology',
    isPrivate: false,
  },
  {
    id: 103,
    title: 'Web3 & Blockchain Expo',
    description: 'Explore the next generation of the internet, decentralized finance, and blockchain solutions.',
    imageSrc: 'https://images.unsplash.com/photo-1639762681485-074b7f4f8352?w=800&q=80',
    date: 'Sep 05, 2026',
    location: 'SMX Convention Center',
    attendees: '3,000',
    category: 'Technology',
    isPrivate: false,
  },
  {
    id: 104,
    title: 'Cybersecurity Symposium',
    description: 'Learn the latest strategies in digital defense, ethical hacking, and data protection.',
    imageSrc: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
    date: 'Oct 12, 2026',
    location: 'Ortigas Center',
    attendees: '800',
    category: 'Technology',
    isPrivate: true,
  },

  // Design
  {
    id: 201,
    title: 'Manila Design Week',
    description: 'A week-long celebration of design, creativity, and innovation across multiple venues in Manila.',
    imageSrc: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80',
    date: 'Aug 3, 2026',
    location: 'Makati City',
    attendees: '4,200',
    category: 'Design',
    isPrivate: false,
  },
  {
    id: 202,
    title: 'UX/UI Masters Workshop',
    description: 'Intensive hands-on workshop covering user research, prototyping, and modern interface design.',
    imageSrc: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    date: 'Jul 20, 2026',
    location: 'BGC, Taguig City',
    attendees: '150',
    category: 'Design',
    isPrivate: false,
  },
  {
    id: 203,
    title: 'Architecture Visionaries',
    description: 'Showcasing the future of sustainable urban design and architectural innovation.',
    imageSrc: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
    date: 'Sep 18, 2026',
    location: 'Quezon City',
    attendees: '600',
    category: 'Design',
    isPrivate: false,
  },
  {
    id: 204,
    title: 'Digital Art Showcase',
    description: 'An immersive gallery experience featuring interactive installations and digital masterpieces.',
    imageSrc: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800&q=80',
    date: 'Nov 02, 2026',
    location: 'BGC Arts Center',
    attendees: '2,000',
    category: 'Design',
    isPrivate: false,
  },

  // Entertainment
  {
    id: 301,
    title: 'Music & Arts Festival',
    description: 'A vibrant outdoor festival featuring live performances, art installations, and local food vendors.',
    imageSrc: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80',
    date: 'Sep 12, 2026',
    location: 'Clark, Pampanga',
    attendees: '8,000',
    category: 'Entertainment',
    isPrivate: false,
  },
  {
    id: 302,
    title: 'Indie Film Premiere',
    description: 'Exclusive screening of award-winning independent films followed by director Q&A sessions.',
    imageSrc: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80',
    date: 'Aug 15, 2026',
    location: 'UP Diliman',
    attendees: '400',
    category: 'Entertainment',
    isPrivate: false,
  },
  {
    id: 303,
    title: 'Comedy Night Live',
    description: 'An evening of non-stop laughter featuring top local and international stand-up comedians.',
    imageSrc: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&q=80',
    date: 'Jul 30, 2026',
    location: 'Makati City',
    attendees: '500',
    category: 'Entertainment',
    isPrivate: false,
  },
  {
    id: 304,
    title: 'Pop Culture Con',
    description: 'The ultimate fan convention for comics, anime, gaming, and collectible enthusiasts.',
    imageSrc: 'https://images.unsplash.com/photo-1612036782180-6f0b6ce846ce?w=800&q=80',
    date: 'Oct 24, 2026',
    location: 'World Trade Center',
    attendees: '15,000',
    category: 'Entertainment',
    isPrivate: false,
  },

  // Wellness
  {
    id: 401,
    title: 'Wellness & Mindfulness Retreat',
    description: 'A weekend retreat focused on mental health, yoga, meditation, and holistic wellness practices.',
    imageSrc: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
    date: 'Aug 20, 2026',
    location: 'Tagaytay City',
    attendees: '200',
    category: 'Wellness',
    isPrivate: false,
  },
  {
    id: 402,
    title: 'Urban Marathon 2026',
    description: 'Join thousands of runners in the annual city marathon promoting health and community fitness.',
    imageSrc: 'https://images.unsplash.com/photo-1552674605-15c2145efa38?w=800&q=80',
    date: 'Nov 15, 2026',
    location: 'Roxas Boulevard',
    attendees: '10,000',
    category: 'Wellness',
    isPrivate: false,
  },
  {
    id: 403,
    title: 'Plant-Based Food Expo',
    description: 'Discover the latest in vegan cuisine, sustainable eating, and healthy lifestyle products.',
    imageSrc: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    date: 'Sep 28, 2026',
    location: 'Alabang, Muntinlupa',
    attendees: '3,500',
    category: 'Wellness',
    isPrivate: false,
  },
  {
    id: 404,
    title: 'Sound Healing Session',
    description: 'Experience deep relaxation and stress relief through therapeutic sound bath frequencies.',
    imageSrc: 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=800&q=80',
    date: 'Jul 22, 2026',
    location: 'Makati City',
    attendees: '50',
    category: 'Wellness',
    isPrivate: true,
  },

  // Business
  {
    id: 501,
    title: 'Corporate Leadership Forum',
    description: 'An invite-only gathering of C-suite executives discussing the future of business in Asia Pacific.',
    imageSrc: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&q=80',
    date: 'Oct 5, 2026',
    location: 'Pasig City',
    attendees: '150',
    category: 'Business',
    isPrivate: true,
  },
  {
    id: 502,
    title: 'Startup Founders Mixer',
    description: 'An exclusive networking event for startup founders, VCs, and angel investors in the Philippines.',
    imageSrc: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80',
    date: 'Jul 28, 2026',
    location: 'Ortigas Center',
    attendees: '350',
    category: 'Business',
    isPrivate: true,
  },
  {
    id: 503,
    title: 'E-Commerce Growth Summit',
    description: 'Master the strategies and tools to scale your online retail business in a competitive market.',
    imageSrc: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
    date: 'Aug 10, 2026',
    location: 'BGC, Taguig City',
    attendees: '1,500',
    category: 'Business',
    isPrivate: false,
  },
  {
    id: 504,
    title: 'Real Estate Investment Masterclass',
    description: 'Learn property market trends and investment strategies from top industry tycoons.',
    imageSrc: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
    date: 'Sep 20, 2026',
    location: 'Makati City',
    attendees: '800',
    category: 'Business',
    isPrivate: false,
  },
  // Food & Culture
  {
    id: 601,
    title: 'Food & Culture Expo',
    description: 'Discover diverse cuisines, cultural performances, and artisanal crafts from across the Philippines.',
    imageSrc: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    date: 'Sep 25, 2026',
    location: 'SM Mall of Asia',
    attendees: '12,000',
    category: 'Food & Culture',
    isPrivate: false,
  },
  {
    id: 602,
    title: 'Asian Street Food Festival',
    description: 'A culinary journey through the best street food from various Asian countries.',
    imageSrc: 'https://images.unsplash.com/photo-1548943487-a2e4143fa9ce?w=800&q=80',
    date: 'Oct 15, 2026',
    location: 'BGC Amphitheater',
    attendees: '5,000',
    category: 'Food & Culture',
    isPrivate: false,
  },

  // Gaming
  {
    id: 701,
    title: 'Esports Championship Finals',
    description: 'Watch the top esports teams from Southeast Asia compete for the regional championship title.',
    imageSrc: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80',
    date: 'Nov 10, 2026',
    location: 'Philippine Arena',
    attendees: '15,000',
    category: 'Gaming',
    isPrivate: false,
  },
  {
    id: 702,
    title: 'Indie Game Showcase',
    description: 'Play and discover unreleased indie games from local developers.',
    imageSrc: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800&q=80',
    date: 'Dec 05, 2026',
    location: 'Makati City',
    attendees: '1,500',
    category: 'Gaming',
    isPrivate: false,
  },

  // Networking
  {
    id: 801,
    title: 'Tech Founders Meetup',
    description: 'An exclusive networking event for startup founders and angel investors.',
    imageSrc: 'https://images.unsplash.com/photo-1515169067868-5387ec356754?w=800&q=80',
    date: 'Aug 05, 2026',
    location: 'Ortigas Center',
    attendees: '300',
    category: 'Networking',
    isPrivate: true,
  },
  {
    id: 802,
    title: 'Women in Leadership Mixer',
    description: 'Empowering conversations and networking for female executives and entrepreneurs.',
    imageSrc: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80',
    date: 'Sep 10, 2026',
    location: 'BGC, Taguig City',
    attendees: '400',
    category: 'Networking',
    isPrivate: false,
  },
];

export function useDiscoverViewModel() {
  const publicEvents = allEvents.filter((e) => !e.isPrivate);
  const privateEvents = allEvents.filter((e) => e.isPrivate);

  // Featured events for the CardStack (first 5 public)
  const featuredEvents = publicEvents.slice(0, 5);

  return {
    allEvents,
    publicEvents,
    privateEvents,
    featuredEvents,
  };
}
